<?php

use Illuminate\Database\Seeder;

use App\Pet;


class PetsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //create pet for sell.......................1
        $pet = new Pet;
        $pet->category_id      = 1;
        $pet->title            = 'German Shefard';
        $pet->description      = 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident quo ab eum doloribus vitae consequuntur voluptatibus! Ea ducimus sed aperiam suscipit, laudantium, excepturi omnis dignissimos dolor a enim quidem impedit! Illum accusantium dolorem, expedita velit aliquam eligendi assumenda modi laboriosam consequatur impedit provident in ducimus commodi! Libero repellat, perferendis accusantium in debitis impedit dicta molestiae porro, deleniti suscipit, fuga distinctio! Sequi, dicta velit ex, delectus dolorem ullam odit blanditiis rerum dolore libero unde non at enim est obcaecati, aspernatur quos maiores illum. Praesentium temporibus deleniti, tempore rem vero, ipsa porro numquam deserunt consequatur magni sequi, natus nemo voluptatibus? Iusto, laudantium enim saepe ab culpa ducimus dolorum eligendi veniam? Recusandae voluptates vel mollitia aspernatur officia vitae, quo repellat est aut, expedita voluptatibus consectetur. Voluptatum, nesciunt? Odit numquam culpa optio, eos magni dolorem est voluptatum, 
                                    veniam provident eius odio, totam quos. Enim laborum sed et qui ipsum aliquam doloribus, fugiat voluptates officia repellendus cum accusamus necessitatibus voluptatum quis at! Atque officia, cupiditate vitae pariatur natus maiores veniam quis libero accusantium, iusto inventore, tenetur nisi tempora veritatis corporis minima provident excepturi itaque dolor. Placeat magni, alias nam quos facere similique eius temporibus quibusdam? Cumque quos illo fuga dolor nisi cum consequatur deleniti nesciunt earum! Vero iusto earum, eius aspernatur consectetur quisquam vel nulla quia officiis ipsa soluta rem laborum dolore labore eum numquam alias repellat tempore excepturi, perspiciatis ducimus eos at sit quasi. Voluptates est nulla commodi vero dignissimos nemo corrupti consequuntur doloribus in reprehenderit! Perferendis assumenda, dolores, mollitia praesentium modi ducimus dolorum sed ipsa saepe debitis repellat atque sunt corrupti! Numquam inventore corrupti aperiam ea vel facilis pariatur porro laborum fugit, quod possimus tempore officia!
                                    Distinctio, nesciunt? Molestiae, aperiam quod labore nobis rerum nisi, doloremque delectus quo, perspiciatis magni tempora fugit porro. Inventore quidem quia facere ea officia hic! Eaque assumenda quam suscipit totam vitae ipsam fuga iure delectus debitis consequuntur cum, sapiente ratione quas, nam nostrum repellat animi asperiores quaerat ex. Error doloremque ab blanditiis nostrum corrupti magnam nobis eum neque rem, incidunt earum facilis natus explicabo in aut. Officia quibusdam ducimus soluta quis nam labore beatae id necessitatibus, nisi, ea minima fuga? Earum nostrum dignissimos quod atque. Expedita nemo magnam tenetur rerum minima ab quaerat? Voluptatum ratione sint repellat. Doloremque, vel ipsa possimus quas recusandae officia sapiente sunt quibusdam aperiam voluptas repellendus atque voluptatibus quae dolorum modi itaque accusamus eum necessitatibus delectus dolorem laudantium. Deserunt, officiis mollitia fuga est aliquam aut nisi beatae! Reprehenderit debitis ab iusto inventore, libero fuga placeat voluptates pariatur neque expedita! 
                                    Ab nostrum illo asperiores quod, voluptatibus consectetur omnis dignissimos quasi enim facilis, quas modi quisquam! Fugiat mollitia expedita magnam tenetur quod, sint veritatis reiciendis eaque officia cupiditate iste assumenda officiis voluptatem et consequatur dignissimos quis accusantium deserunt, enim accusamus! Similique atque fugit temporibus, odit nihil ad explicabo reprehenderit exercitationem possimus ipsa enim quo suscipit saepe commodi, ullam accusantium ex rerum reiciendis cumque ut. Nam ipsa ad harum molestiae architecto, perferendis amet esse, omnis alias quos ipsam repellendus, sunt dignissimos odio sint sit voluptate velit voluptas!';
        $pet->price            = 15000;
        $pet->stock            = 5;
        $pet->discount         = 20;
        $pet->slug             = 'German Shefard';
        $pet->image            = '/images/uploads/pets_img/dog.jpg';
        $pet->save();


         //create pet for sell.......................2
         $pet = new Pet;
         $pet->category_id      = 2;
         $pet->title            = 'Persian cat';
         $pet->description      = 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident quo ab eum doloribus vitae consequuntur voluptatibus! Ea ducimus sed aperiam suscipit, laudantium, excepturi omnis dignissimos dolor a enim quidem impedit! Illum accusantium dolorem, expedita velit aliquam eligendi assumenda modi laboriosam consequatur impedit provident in ducimus commodi! Libero repellat, perferendis accusantium in debitis impedit dicta molestiae porro, deleniti suscipit, fuga distinctio! Sequi, dicta velit ex, delectus dolorem ullam odit blanditiis rerum dolore libero unde non at enim est obcaecati, aspernatur quos maiores illum. Praesentium temporibus deleniti, tempore rem vero, ipsa porro numquam deserunt consequatur magni sequi, natus nemo voluptatibus? Iusto, laudantium enim saepe ab culpa ducimus dolorum eligendi veniam? Recusandae voluptates vel mollitia aspernatur officia vitae, quo repellat est aut, expedita voluptatibus consectetur. Voluptatum, nesciunt? Odit numquam culpa optio, eos magni dolorem est voluptatum, 
                                     veniam provident eius odio, totam quos. Enim laborum sed et qui ipsum aliquam doloribus, fugiat voluptates officia repellendus cum accusamus necessitatibus voluptatum quis at! Atque officia, cupiditate vitae pariatur natus maiores veniam quis libero accusantium, iusto inventore, tenetur nisi tempora veritatis corporis minima provident excepturi itaque dolor. Placeat magni, alias nam quos facere similique eius temporibus quibusdam? Cumque quos illo fuga dolor nisi cum consequatur deleniti nesciunt earum! Vero iusto earum, eius aspernatur consectetur quisquam vel nulla quia officiis ipsa soluta rem laborum dolore labore eum numquam alias repellat tempore excepturi, perspiciatis ducimus eos at sit quasi. Voluptates est nulla commodi vero dignissimos nemo corrupti consequuntur doloribus in reprehenderit! Perferendis assumenda, dolores, mollitia praesentium modi ducimus dolorum sed ipsa saepe debitis repellat atque sunt corrupti! Numquam inventore corrupti aperiam ea vel facilis pariatur porro laborum fugit, quod possimus tempore officia!
                                     Distinctio, nesciunt? Molestiae, aperiam quod labore nobis rerum nisi, doloremque delectus quo, perspiciatis magni tempora fugit porro. Inventore quidem quia facere ea officia hic! Eaque assumenda quam suscipit totam vitae ipsam fuga iure delectus debitis consequuntur cum, sapiente ratione quas, nam nostrum repellat animi asperiores quaerat ex. Error doloremque ab blanditiis nostrum corrupti magnam nobis eum neque rem, incidunt earum facilis natus explicabo in aut. Officia quibusdam ducimus soluta quis nam labore beatae id necessitatibus, nisi, ea minima fuga? Earum nostrum dignissimos quod atque. Expedita nemo magnam tenetur rerum minima ab quaerat? Voluptatum ratione sint repellat. Doloremque, vel ipsa possimus quas recusandae officia sapiente sunt quibusdam aperiam voluptas repellendus atque voluptatibus quae dolorum modi itaque accusamus eum necessitatibus delectus dolorem laudantium. Deserunt, officiis mollitia fuga est aliquam aut nisi beatae! Reprehenderit debitis ab iusto inventore, libero fuga placeat voluptates pariatur neque expedita! 
                                     Ab nostrum illo asperiores quod, voluptatibus consectetur omnis dignissimos quasi enim facilis, quas modi quisquam! Fugiat mollitia expedita magnam tenetur quod, sint veritatis reiciendis eaque officia cupiditate iste assumenda officiis voluptatem et consequatur dignissimos quis accusantium deserunt, enim accusamus! Similique atque fugit temporibus, odit nihil ad explicabo reprehenderit exercitationem possimus ipsa enim quo suscipit saepe commodi, ullam accusantium ex rerum reiciendis cumque ut. Nam ipsa ad harum molestiae architecto, perferendis amet esse, omnis alias quos ipsam repellendus, sunt dignissimos odio sint sit voluptate velit voluptas!';
         $pet->price            = 10000;
         $pet->stock            = 20;
         $pet->discount         = 25;
         $pet->slug             = 'Persian cat';
         $pet->image            = '/images/uploads/pets_img/cat.jpg';
         $pet->save();

          //create pet for sell.......................3
        $pet = new Pet;
        $pet->category_id      = 3;
        $pet->title            = 'African Gray Parrot';
        $pet->description      = 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident quo ab eum doloribus vitae consequuntur voluptatibus! Ea ducimus sed aperiam suscipit, laudantium, excepturi omnis dignissimos dolor a enim quidem impedit! Illum accusantium dolorem, expedita velit aliquam eligendi assumenda modi laboriosam consequatur impedit provident in ducimus commodi! Libero repellat, perferendis accusantium in debitis impedit dicta molestiae porro, deleniti suscipit, fuga distinctio! Sequi, dicta velit ex, delectus dolorem ullam odit blanditiis rerum dolore libero unde non at enim est obcaecati, aspernatur quos maiores illum. Praesentium temporibus deleniti, tempore rem vero, ipsa porro numquam deserunt consequatur magni sequi, natus nemo voluptatibus? Iusto, laudantium enim saepe ab culpa ducimus dolorum eligendi veniam? Recusandae voluptates vel mollitia aspernatur officia vitae, quo repellat est aut, expedita voluptatibus consectetur. Voluptatum, nesciunt? Odit numquam culpa optio, eos magni dolorem est voluptatum, 
                                    veniam provident eius odio, totam quos. Enim laborum sed et qui ipsum aliquam doloribus, fugiat voluptates officia repellendus cum accusamus necessitatibus voluptatum quis at! Atque officia, cupiditate vitae pariatur natus maiores veniam quis libero accusantium, iusto inventore, tenetur nisi tempora veritatis corporis minima provident excepturi itaque dolor. Placeat magni, alias nam quos facere similique eius temporibus quibusdam? Cumque quos illo fuga dolor nisi cum consequatur deleniti nesciunt earum! Vero iusto earum, eius aspernatur consectetur quisquam vel nulla quia officiis ipsa soluta rem laborum dolore labore eum numquam alias repellat tempore excepturi, perspiciatis ducimus eos at sit quasi. Voluptates est nulla commodi vero dignissimos nemo corrupti consequuntur doloribus in reprehenderit! Perferendis assumenda, dolores, mollitia praesentium modi ducimus dolorum sed ipsa saepe debitis repellat atque sunt corrupti! Numquam inventore corrupti aperiam ea vel facilis pariatur porro laborum fugit, quod possimus tempore officia!
                                    Distinctio, nesciunt? Molestiae, aperiam quod labore nobis rerum nisi, doloremque delectus quo, perspiciatis magni tempora fugit porro. Inventore quidem quia facere ea officia hic! Eaque assumenda quam suscipit totam vitae ipsam fuga iure delectus debitis consequuntur cum, sapiente ratione quas, nam nostrum repellat animi asperiores quaerat ex. Error doloremque ab blanditiis nostrum corrupti magnam nobis eum neque rem, incidunt earum facilis natus explicabo in aut. Officia quibusdam ducimus soluta quis nam labore beatae id necessitatibus, nisi, ea minima fuga? Earum nostrum dignissimos quod atque. Expedita nemo magnam tenetur rerum minima ab quaerat? Voluptatum ratione sint repellat. Doloremque, vel ipsa possimus quas recusandae officia sapiente sunt quibusdam aperiam voluptas repellendus atque voluptatibus quae dolorum modi itaque accusamus eum necessitatibus delectus dolorem laudantium. Deserunt, officiis mollitia fuga est aliquam aut nisi beatae! Reprehenderit debitis ab iusto inventore, libero fuga placeat voluptates pariatur neque expedita! 
                                    Ab nostrum illo asperiores quod, voluptatibus consectetur omnis dignissimos quasi enim facilis, quas modi quisquam! Fugiat mollitia expedita magnam tenetur quod, sint veritatis reiciendis eaque officia cupiditate iste assumenda officiis voluptatem et consequatur dignissimos quis accusantium deserunt, enim accusamus! Similique atque fugit temporibus, odit nihil ad explicabo reprehenderit exercitationem possimus ipsa enim quo suscipit saepe commodi, ullam accusantium ex rerum reiciendis cumque ut. Nam ipsa ad harum molestiae architecto, perferendis amet esse, omnis alias quos ipsam repellendus, sunt dignissimos odio sint sit voluptate velit voluptas!';
        $pet->price            = 50000;
        $pet->stock            = 2;
        $pet->discount         = 10;
        $pet->slug             = 'African Gray Parrot';
        $pet->image            = '/images/uploads/pets_img/birds.jpg';
        $pet->save();

         //create pet for sell.......................4
         $pet = new Pet;
         $pet->category_id      = 4;
         $pet->title            = 'Thai Rabbit';
         $pet->description      = 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident quo ab eum doloribus vitae consequuntur voluptatibus! Ea ducimus sed aperiam suscipit, laudantium, excepturi omnis dignissimos dolor a enim quidem impedit! Illum accusantium dolorem, expedita velit aliquam eligendi assumenda modi laboriosam consequatur impedit provident in ducimus commodi! Libero repellat, perferendis accusantium in debitis impedit dicta molestiae porro, deleniti suscipit, fuga distinctio! Sequi, dicta velit ex, delectus dolorem ullam odit blanditiis rerum dolore libero unde non at enim est obcaecati, aspernatur quos maiores illum. Praesentium temporibus deleniti, tempore rem vero, ipsa porro numquam deserunt consequatur magni sequi, natus nemo voluptatibus? Iusto, laudantium enim saepe ab culpa ducimus dolorum eligendi veniam? Recusandae voluptates vel mollitia aspernatur officia vitae, quo repellat est aut, expedita voluptatibus consectetur. Voluptatum, nesciunt? Odit numquam culpa optio, eos magni dolorem est voluptatum, 
                                     veniam provident eius odio, totam quos. Enim laborum sed et qui ipsum aliquam doloribus, fugiat voluptates officia repellendus cum accusamus necessitatibus voluptatum quis at! Atque officia, cupiditate vitae pariatur natus maiores veniam quis libero accusantium, iusto inventore, tenetur nisi tempora veritatis corporis minima provident excepturi itaque dolor. Placeat magni, alias nam quos facere similique eius temporibus quibusdam? Cumque quos illo fuga dolor nisi cum consequatur deleniti nesciunt earum! Vero iusto earum, eius aspernatur consectetur quisquam vel nulla quia officiis ipsa soluta rem laborum dolore labore eum numquam alias repellat tempore excepturi, perspiciatis ducimus eos at sit quasi. Voluptates est nulla commodi vero dignissimos nemo corrupti consequuntur doloribus in reprehenderit! Perferendis assumenda, dolores, mollitia praesentium modi ducimus dolorum sed ipsa saepe debitis repellat atque sunt corrupti! Numquam inventore corrupti aperiam ea vel facilis pariatur porro laborum fugit, quod possimus tempore officia!
                                     Distinctio, nesciunt? Molestiae, aperiam quod labore nobis rerum nisi, doloremque delectus quo, perspiciatis magni tempora fugit porro. Inventore quidem quia facere ea officia hic! Eaque assumenda quam suscipit totam vitae ipsam fuga iure delectus debitis consequuntur cum, sapiente ratione quas, nam nostrum repellat animi asperiores quaerat ex. Error doloremque ab blanditiis nostrum corrupti magnam nobis eum neque rem, incidunt earum facilis natus explicabo in aut. Officia quibusdam ducimus soluta quis nam labore beatae id necessitatibus, nisi, ea minima fuga? Earum nostrum dignissimos quod atque. Expedita nemo magnam tenetur rerum minima ab quaerat? Voluptatum ratione sint repellat. Doloremque, vel ipsa possimus quas recusandae officia sapiente sunt quibusdam aperiam voluptas repellendus atque voluptatibus quae dolorum modi itaque accusamus eum necessitatibus delectus dolorem laudantium. Deserunt, officiis mollitia fuga est aliquam aut nisi beatae! Reprehenderit debitis ab iusto inventore, libero fuga placeat voluptates pariatur neque expedita! 
                                     Ab nostrum illo asperiores quod, voluptatibus consectetur omnis dignissimos quasi enim facilis, quas modi quisquam! Fugiat mollitia expedita magnam tenetur quod, sint veritatis reiciendis eaque officia cupiditate iste assumenda officiis voluptatem et consequatur dignissimos quis accusantium deserunt, enim accusamus! Similique atque fugit temporibus, odit nihil ad explicabo reprehenderit exercitationem possimus ipsa enim quo suscipit saepe commodi, ullam accusantium ex rerum reiciendis cumque ut. Nam ipsa ad harum molestiae architecto, perferendis amet esse, omnis alias quos ipsam repellendus, sunt dignissimos odio sint sit voluptate velit voluptas!';
         $pet->price            = 500;
         $pet->stock            = 50;
         $pet->discount         = 5;
         $pet->slug             = 'Thai Rabbit';
         $pet->image            = '/images/uploads/pets_img/rabbit.jpg';
         $pet->save();


          //create pet for sell.......................5
        $pet = new Pet;
        $pet->category_id      = 1;
        $pet->title            = 'usa bulldog';
        $pet->description      = 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident quo ab eum doloribus vitae consequuntur voluptatibus! Ea ducimus sed aperiam suscipit, laudantium, excepturi omnis dignissimos dolor a enim quidem impedit! Illum accusantium dolorem, expedita velit aliquam eligendi assumenda modi laboriosam consequatur impedit provident in ducimus commodi! Libero repellat, perferendis accusantium in debitis impedit dicta molestiae porro, deleniti suscipit, fuga distinctio! Sequi, dicta velit ex, delectus dolorem ullam odit blanditiis rerum dolore libero unde non at enim est obcaecati, aspernatur quos maiores illum. Praesentium temporibus deleniti, tempore rem vero, ipsa porro numquam deserunt consequatur magni sequi, natus nemo voluptatibus? Iusto, laudantium enim saepe ab culpa ducimus dolorum eligendi veniam? Recusandae voluptates vel mollitia aspernatur officia vitae, quo repellat est aut, expedita voluptatibus consectetur. Voluptatum, nesciunt? Odit numquam culpa optio, eos magni dolorem est voluptatum, 
                                    veniam provident eius odio, totam quos. Enim laborum sed et qui ipsum aliquam doloribus, fugiat voluptates officia repellendus cum accusamus necessitatibus voluptatum quis at! Atque officia, cupiditate vitae pariatur natus maiores veniam quis libero accusantium, iusto inventore, tenetur nisi tempora veritatis corporis minima provident excepturi itaque dolor. Placeat magni, alias nam quos facere similique eius temporibus quibusdam? Cumque quos illo fuga dolor nisi cum consequatur deleniti nesciunt earum! Vero iusto earum, eius aspernatur consectetur quisquam vel nulla quia officiis ipsa soluta rem laborum dolore labore eum numquam alias repellat tempore excepturi, perspiciatis ducimus eos at sit quasi. Voluptates est nulla commodi vero dignissimos nemo corrupti consequuntur doloribus in reprehenderit! Perferendis assumenda, dolores, mollitia praesentium modi ducimus dolorum sed ipsa saepe debitis repellat atque sunt corrupti! Numquam inventore corrupti aperiam ea vel facilis pariatur porro laborum fugit, quod possimus tempore officia!
                                    Distinctio, nesciunt? Molestiae, aperiam quod labore nobis rerum nisi, doloremque delectus quo, perspiciatis magni tempora fugit porro. Inventore quidem quia facere ea officia hic! Eaque assumenda quam suscipit totam vitae ipsam fuga iure delectus debitis consequuntur cum, sapiente ratione quas, nam nostrum repellat animi asperiores quaerat ex. Error doloremque ab blanditiis nostrum corrupti magnam nobis eum neque rem, incidunt earum facilis natus explicabo in aut. Officia quibusdam ducimus soluta quis nam labore beatae id necessitatibus, nisi, ea minima fuga? Earum nostrum dignissimos quod atque. Expedita nemo magnam tenetur rerum minima ab quaerat? Voluptatum ratione sint repellat. Doloremque, vel ipsa possimus quas recusandae officia sapiente sunt quibusdam aperiam voluptas repellendus atque voluptatibus quae dolorum modi itaque accusamus eum necessitatibus delectus dolorem laudantium. Deserunt, officiis mollitia fuga est aliquam aut nisi beatae! Reprehenderit debitis ab iusto inventore, libero fuga placeat voluptates pariatur neque expedita! 
                                    Ab nostrum illo asperiores quod, voluptatibus consectetur omnis dignissimos quasi enim facilis, quas modi quisquam! Fugiat mollitia expedita magnam tenetur quod, sint veritatis reiciendis eaque officia cupiditate iste assumenda officiis voluptatem et consequatur dignissimos quis accusantium deserunt, enim accusamus! Similique atque fugit temporibus, odit nihil ad explicabo reprehenderit exercitationem possimus ipsa enim quo suscipit saepe commodi, ullam accusantium ex rerum reiciendis cumque ut. Nam ipsa ad harum molestiae architecto, perferendis amet esse, omnis alias quos ipsam repellendus, sunt dignissimos odio sint sit voluptate velit voluptas!';
        $pet->price            = 75000;
        $pet->stock            = 4;
        $pet->slug             = 'usa bulldog';
        $pet->image            = '/images/uploads/pets_img/dog.jpg';
        $pet->save();

         //create pet for sell.......................6
         $pet = new Pet;
         $pet->category_id      = 2;
         $pet->title            = 'african cat';
         $pet->description      = 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident quo ab eum doloribus vitae consequuntur voluptatibus! Ea ducimus sed aperiam suscipit, laudantium, excepturi omnis dignissimos dolor a enim quidem impedit! Illum accusantium dolorem, expedita velit aliquam eligendi assumenda modi laboriosam consequatur impedit provident in ducimus commodi! Libero repellat, perferendis accusantium in debitis impedit dicta molestiae porro, deleniti suscipit, fuga distinctio! Sequi, dicta velit ex, delectus dolorem ullam odit blanditiis rerum dolore libero unde non at enim est obcaecati, aspernatur quos maiores illum. Praesentium temporibus deleniti, tempore rem vero, ipsa porro numquam deserunt consequatur magni sequi, natus nemo voluptatibus? Iusto, laudantium enim saepe ab culpa ducimus dolorum eligendi veniam? Recusandae voluptates vel mollitia aspernatur officia vitae, quo repellat est aut, expedita voluptatibus consectetur. Voluptatum, nesciunt? Odit numquam culpa optio, eos magni dolorem est voluptatum, 
                                     veniam provident eius odio, totam quos. Enim laborum sed et qui ipsum aliquam doloribus, fugiat voluptates officia repellendus cum accusamus necessitatibus voluptatum quis at! Atque officia, cupiditate vitae pariatur natus maiores veniam quis libero accusantium, iusto inventore, tenetur nisi tempora veritatis corporis minima provident excepturi itaque dolor. Placeat magni, alias nam quos facere similique eius temporibus quibusdam? Cumque quos illo fuga dolor nisi cum consequatur deleniti nesciunt earum! Vero iusto earum, eius aspernatur consectetur quisquam vel nulla quia officiis ipsa soluta rem laborum dolore labore eum numquam alias repellat tempore excepturi, perspiciatis ducimus eos at sit quasi. Voluptates est nulla commodi vero dignissimos nemo corrupti consequuntur doloribus in reprehenderit! Perferendis assumenda, dolores, mollitia praesentium modi ducimus dolorum sed ipsa saepe debitis repellat atque sunt corrupti! Numquam inventore corrupti aperiam ea vel facilis pariatur porro laborum fugit, quod possimus tempore officia!
                                     Distinctio, nesciunt? Molestiae, aperiam quod labore nobis rerum nisi, doloremque delectus quo, perspiciatis magni tempora fugit porro. Inventore quidem quia facere ea officia hic! Eaque assumenda quam suscipit totam vitae ipsam fuga iure delectus debitis consequuntur cum, sapiente ratione quas, nam nostrum repellat animi asperiores quaerat ex. Error doloremque ab blanditiis nostrum corrupti magnam nobis eum neque rem, incidunt earum facilis natus explicabo in aut. Officia quibusdam ducimus soluta quis nam labore beatae id necessitatibus, nisi, ea minima fuga? Earum nostrum dignissimos quod atque. Expedita nemo magnam tenetur rerum minima ab quaerat? Voluptatum ratione sint repellat. Doloremque, vel ipsa possimus quas recusandae officia sapiente sunt quibusdam aperiam voluptas repellendus atque voluptatibus quae dolorum modi itaque accusamus eum necessitatibus delectus dolorem laudantium. Deserunt, officiis mollitia fuga est aliquam aut nisi beatae! Reprehenderit debitis ab iusto inventore, libero fuga placeat voluptates pariatur neque expedita! 
                                     Ab nostrum illo asperiores quod, voluptatibus consectetur omnis dignissimos quasi enim facilis, quas modi quisquam! Fugiat mollitia expedita magnam tenetur quod, sint veritatis reiciendis eaque officia cupiditate iste assumenda officiis voluptatem et consequatur dignissimos quis accusantium deserunt, enim accusamus! Similique atque fugit temporibus, odit nihil ad explicabo reprehenderit exercitationem possimus ipsa enim quo suscipit saepe commodi, ullam accusantium ex rerum reiciendis cumque ut. Nam ipsa ad harum molestiae architecto, perferendis amet esse, omnis alias quos ipsam repellendus, sunt dignissimos odio sint sit voluptate velit voluptas!';
         $pet->price            = 2500;
         $pet->stock            = 12;
         $pet->slug             = 'african cat';
         $pet->image            = '/images/uploads/pets_img/cat.jpg';
         $pet->save();

          //create pet for sell.......................7
        $pet = new Pet;
        $pet->category_id      = 3;
        $pet->title            = 'macaw';
        $pet->description      = 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident quo ab eum doloribus vitae consequuntur voluptatibus! Ea ducimus sed aperiam suscipit, laudantium, excepturi omnis dignissimos dolor a enim quidem impedit! Illum accusantium dolorem, expedita velit aliquam eligendi assumenda modi laboriosam consequatur impedit provident in ducimus commodi! Libero repellat, perferendis accusantium in debitis impedit dicta molestiae porro, deleniti suscipit, fuga distinctio! Sequi, dicta velit ex, delectus dolorem ullam odit blanditiis rerum dolore libero unde non at enim est obcaecati, aspernatur quos maiores illum. Praesentium temporibus deleniti, tempore rem vero, ipsa porro numquam deserunt consequatur magni sequi, natus nemo voluptatibus? Iusto, laudantium enim saepe ab culpa ducimus dolorum eligendi veniam? Recusandae voluptates vel mollitia aspernatur officia vitae, quo repellat est aut, expedita voluptatibus consectetur. Voluptatum, nesciunt? Odit numquam culpa optio, eos magni dolorem est voluptatum, 
                                    veniam provident eius odio, totam quos. Enim laborum sed et qui ipsum aliquam doloribus, fugiat voluptates officia repellendus cum accusamus necessitatibus voluptatum quis at! Atque officia, cupiditate vitae pariatur natus maiores veniam quis libero accusantium, iusto inventore, tenetur nisi tempora veritatis corporis minima provident excepturi itaque dolor. Placeat magni, alias nam quos facere similique eius temporibus quibusdam? Cumque quos illo fuga dolor nisi cum consequatur deleniti nesciunt earum! Vero iusto earum, eius aspernatur consectetur quisquam vel nulla quia officiis ipsa soluta rem laborum dolore labore eum numquam alias repellat tempore excepturi, perspiciatis ducimus eos at sit quasi. Voluptates est nulla commodi vero dignissimos nemo corrupti consequuntur doloribus in reprehenderit! Perferendis assumenda, dolores, mollitia praesentium modi ducimus dolorum sed ipsa saepe debitis repellat atque sunt corrupti! Numquam inventore corrupti aperiam ea vel facilis pariatur porro laborum fugit, quod possimus tempore officia!
                                    Distinctio, nesciunt? Molestiae, aperiam quod labore nobis rerum nisi, doloremque delectus quo, perspiciatis magni tempora fugit porro. Inventore quidem quia facere ea officia hic! Eaque assumenda quam suscipit totam vitae ipsam fuga iure delectus debitis consequuntur cum, sapiente ratione quas, nam nostrum repellat animi asperiores quaerat ex. Error doloremque ab blanditiis nostrum corrupti magnam nobis eum neque rem, incidunt earum facilis natus explicabo in aut. Officia quibusdam ducimus soluta quis nam labore beatae id necessitatibus, nisi, ea minima fuga? Earum nostrum dignissimos quod atque. Expedita nemo magnam tenetur rerum minima ab quaerat? Voluptatum ratione sint repellat. Doloremque, vel ipsa possimus quas recusandae officia sapiente sunt quibusdam aperiam voluptas repellendus atque voluptatibus quae dolorum modi itaque accusamus eum necessitatibus delectus dolorem laudantium. Deserunt, officiis mollitia fuga est aliquam aut nisi beatae! Reprehenderit debitis ab iusto inventore, libero fuga placeat voluptates pariatur neque expedita! 
                                    Ab nostrum illo asperiores quod, voluptatibus consectetur omnis dignissimos quasi enim facilis, quas modi quisquam! Fugiat mollitia expedita magnam tenetur quod, sint veritatis reiciendis eaque officia cupiditate iste assumenda officiis voluptatem et consequatur dignissimos quis accusantium deserunt, enim accusamus! Similique atque fugit temporibus, odit nihil ad explicabo reprehenderit exercitationem possimus ipsa enim quo suscipit saepe commodi, ullam accusantium ex rerum reiciendis cumque ut. Nam ipsa ad harum molestiae architecto, perferendis amet esse, omnis alias quos ipsam repellendus, sunt dignissimos odio sint sit voluptate velit voluptas!';
        $pet->price            = 150000;
        $pet->stock            = 2;
        $pet->slug             = 'macaw';
        $pet->image            = '/images/uploads/pets_img/birds.jpg';
        $pet->save();

    }
}


